apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alerts
  namespace: claude-monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: monitoring
data:
  claude-code-alerts.yml: |
    groups:
    - name: claude_code_alerts
      interval: 30s
      rules:
      
      # 高成本告警
      - alert: ClaudeCodeHighCostRate
        expr: sum(rate(claude_code_claude_code_cost_usage_USD_total[5m]) * 60) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Claude Code 成本過高"
          description: "過去 5 分鐘的平均成本超過 $1/分鐘"
      
      # Token 使用量過高
      - alert: ClaudeCodeHighTokenUsage
        expr: sum(rate(claude_code_claude_code_token_usage_tokens_total[5m]) * 60) > 100000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Claude Code Token 使用量過高"
          description: "過去 5 分鐘的 Token 使用率超過 100K/分鐘"
      
      # 長時間無活動（可能表示問題）
      - alert: ClaudeCodeNoActivity
        expr: increase(claude_code_claude_code_session_count_total[30m]) == 0
        for: 30m
        labels:
          severity: info
        annotations:
          summary: "Claude Code 無活動"
          description: "過去 30 分鐘沒有新的會話"
      
      # OTEL Collector 健康檢查
      - alert: OTELCollectorDown
        expr: up{job="otel-collector"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "OTEL Collector 離線"
          description: "OTEL Collector 已經離線超過 5 分鐘"