apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: claude-monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        cluster: 'claude-monitoring'


    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
        scrape_interval: 15s
        metrics_path: /metrics

      - job_name: 'otel-collector'
        static_configs:
          - targets: ['dev-otel-collector:8888']
        scrape_interval: 15s
        metrics_path: /metrics

      - job_name: 'claude-code-metrics'
        static_configs:
          - targets: ['dev-otel-collector:8889']
        scrape_interval: 15s
        metrics_path: /metrics
        metric_relabel_configs:
          - source_labels: [__name__]
            regex: 'claude_code_.*'
            action: keep

    alerting:
      alertmanagers:
        - static_configs:
            - targets: []