apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: claude-monitoring
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/component: telemetry
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
            cors:
              allowed_origins:
                - "*"
              allowed_headers:
                - "*"

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
        send_batch_max_size: 2048

      memory_limiter:
        limit_mib: 512
        check_interval: 1s

      resource:
        attributes:
          - key: service.name
            value: claude-code
            action: upsert

      attributes:
        actions:
          - key: environment
            action: upsert
            value: "development"

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
        namespace: claude_code
        const_labels:
          service: claude-code
        send_timestamps: true
        metric_expiration: 180m
        enable_open_metrics: true

      debug:
        verbosity: normal

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, resource, attributes, batch]
          exporters: [prometheus, debug]
        
        traces:
          receivers: [otlp]
          processors: [memory_limiter, resource, batch]
          exporters: [debug]
        
        logs:
          receivers: [otlp]
          processors: [memory_limiter, resource, batch]
          exporters: [debug]

      extensions: []

      telemetry:
        logs:
          level: info
        metrics:
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: '0.0.0.0'
                    port: 8888