apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: claude-monitoring
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/component: telemetry
spec:
  selector:
    app.kubernetes.io/name: otel-collector
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
    protocol: TCP
  - name: otlp-http
    port: 4318
    targetPort: 4318
    protocol: TCP
  - name: metrics
    port: 8888
    targetPort: 8888
    protocol: TCP
  - name: prometheus
    port: 8889
    targetPort: 8889
    protocol: TCP
  type: ClusterIP