apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: claude-monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: visualization
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    root_url = http://localhost:3000/
    [security]
    admin_user = admin
    admin_password = admin

  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: default
      folder: ""
      type: file
      options:
        path: /var/lib/grafana/dashboards

  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://dev-prometheus:9090
      basicAuth: false
      isDefault: true

