apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: claude-monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: visualization
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    root_url = http://localhost:3000/
    [security]
    admin_user = admin
    admin_password = admin

  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://dev-prometheus:9090
      basicAuth: false
      isDefault: true

  claude-code-dashboard.json: |
    {
        "id": null,
        "uid": "claude-code-monitoring-v2",
        "title": "Claude Code Monitoring",
        "tags": ["claude", "code", "monitoring"],
        "timezone": "browser",
        "schemaVersion": 30,
        "version": 1,
        "refresh": "30s",
        "editable": true,
        "fiscalYearStartMonth": 0,
        "graphTooltip": 0,
        "links": [],
        "liveNow": false,
        "panels": [
          {
            "id": 1,
            "title": "Lines of Code Modified",
            "type": "graph",
            "datasource": "Prometheus",
            "targets": [
              {
                "expr": "sum(claude_code_claude_code_lines_of_code_count_total)",
                "legendFormat": "Lines Modified"
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 0}
          },
          {
            "id": 2,
            "title": "Token Usage",
            "type": "graph",
            "datasource": "Prometheus",
            "targets": [
              {
                "expr": "sum by (type) (claude_code_claude_code_token_usage_tokens_total)",
                "legendFormat": "{{type}}"
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 0}
          },
          {
            "id": 3,
            "title": "API Request Cost",
            "type": "graph",
            "datasource": "Prometheus",
            "targets": [
              {
                "expr": "rate(claude_code_claude_code_cost_usage_USD_total[5m])",
                "legendFormat": "Cost per minute"
              }
            ],
            "gridPos": {"h": 8, "w": 24, "x": 0, "y": 8}
          },
          {
            "id": 4,
            "title": "Today's Total Cost",
            "type": "stat",
            "datasource": "Prometheus",
            "fieldConfig": {
              "defaults": {
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "green",
                      "value": null
                    },
                    {
                      "color": "yellow", 
                      "value": 10
                    },
                    {
                      "color": "red",
                      "value": 50
                    }
                  ]
                },
                "unit": "currencyUSD",
                "decimals": 4
              },
              "overrides": []
            },
            "options": {
              "colorMode": "value",
              "graphMode": "area",
              "justifyMode": "auto",
              "orientation": "auto",
              "reduceOptions": {
                "calcs": [
                  "lastNotNull"
                ],
                "fields": "",
                "values": false
              },
              "text": {},
              "textMode": "auto"
            },
            "targets": [
              {
                "expr": "sum(increase(claude_code_claude_code_cost_usage_USD_total[1d]))",
                "legendFormat": "Today's Cost",
                "refId": "A"
              }
            ],
            "gridPos": {"h": 4, "w": 8, "x": 0, "y": 16}
          },
          {
            "id": 5,
            "title": "Yesterday's Total Cost",
            "type": "stat",
            "datasource": "Prometheus",
            "fieldConfig": {
              "defaults": {
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "green",
                      "value": null
                    }
                  ]
                },
                "unit": "currencyUSD",
                "decimals": 4
              },
              "overrides": []
            },
            "options": {
              "colorMode": "value",
              "graphMode": "none",
              "justifyMode": "auto",
              "orientation": "auto",
              "reduceOptions": {
                "calcs": [
                  "lastNotNull"
                ],
                "fields": "",
                "values": false
              },
              "text": {},
              "textMode": "auto"
            },
            "targets": [
              {
                "expr": "sum(increase(claude_code_claude_code_cost_usage_USD_total[1d] offset 1d))",
                "legendFormat": "Yesterday's Cost",
                "refId": "A"
              }
            ],
            "gridPos": {"h": 4, "w": 8, "x": 8, "y": 16}
          },
          {
            "id": 6,
            "title": "Active Time",
            "type": "stat",
            "datasource": "Prometheus",
            "fieldConfig": {
              "defaults": {
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "green",
                      "value": null
                    }
                  ]
                },
                "unit": "s",
                "decimals": 0
              },
              "overrides": []
            },
            "options": {
              "colorMode": "value",
              "graphMode": "area",
              "justifyMode": "auto",
              "orientation": "auto",
              "reduceOptions": {
                "calcs": [
                  "lastNotNull"
                ],
                "fields": "",
                "values": false
              },
              "text": {},
              "textMode": "auto"
            },
            "targets": [
              {
                "expr": "sum(claude_code_claude_code_active_time_seconds_total)",
                "legendFormat": "Active Time",
                "refId": "A"
              }
            ],
            "gridPos": {"h": 4, "w": 8, "x": 16, "y": 16}
          },
          {
            "id": 7,
            "title": "Total Sessions",
            "type": "stat",
            "datasource": "Prometheus",
            "fieldConfig": {
              "defaults": {
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "green",
                      "value": null
                    }
                  ]
                },
                "unit": "short"
              },
              "overrides": []
            },
            "options": {
              "colorMode": "value",
              "graphMode": "none",
              "justifyMode": "center",
              "orientation": "auto",
              "reduceOptions": {
                "calcs": [
                  "sum"
                ],
                "fields": "",
                "values": false
              },
              "text": {
                "titleSize": 20,
                "valueSize": 60
              },
              "textMode": "value"
            },
            "targets": [
              {
                "expr": "scalar(count(count by (session_id) (claude_code_claude_code_cost_usage_USD_total)))",
                "legendFormat": "",
                "refId": "A",
                "format": "table",
                "instant": true
              }
            ],
            "gridPos": {"h": 4, "w": 8, "x": 0, "y": 20}
          },
          {
            "id": 8,
            "title": "Git Commits",
            "type": "stat",
            "datasource": "Prometheus",
            "fieldConfig": {
              "defaults": {
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "green",
                      "value": null
                    }
                  ]
                },
                "unit": "short"
              },
              "overrides": []
            },
            "options": {
              "colorMode": "value",
              "graphMode": "area",
              "justifyMode": "auto",
              "orientation": "auto",
              "reduceOptions": {
                "calcs": [
                  "lastNotNull"
                ],
                "fields": "",
                "values": false
              },
              "text": {},
              "textMode": "auto"
            },
            "targets": [
              {
                "expr": "sum(claude_code_claude_code_commit_count_total)",
                "legendFormat": "Total Commits",
                "refId": "A"
              }
            ],
            "gridPos": {"h": 4, "w": 8, "x": 8, "y": 20}
          },
          {
            "id": 9,
            "title": "Tool Decisions",
            "type": "stat",
            "datasource": "Prometheus",
            "fieldConfig": {
              "defaults": {
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "green",
                      "value": null
                    }
                  ]
                },
                "unit": "short"
              },
              "overrides": []
            },
            "options": {
              "colorMode": "value",
              "graphMode": "area",
              "justifyMode": "auto",
              "orientation": "auto",
              "reduceOptions": {
                "calcs": [
                  "lastNotNull"
                ],
                "fields": "",
                "values": false
              },
              "text": {},
              "textMode": "auto"
            },
            "targets": [
              {
                "expr": "sum(claude_code_claude_code_code_edit_tool_decision_total)",
                "legendFormat": "Tool Decisions",
                "refId": "A"
              }
            ],
            "gridPos": {"h": 4, "w": 8, "x": 16, "y": 20}
          },
          {
            "id": 10,
            "title": "Cost by Model",
            "type": "piechart",
            "datasource": "Prometheus",
            "fieldConfig": {
              "defaults": {
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "green",
                      "value": null
                    }
                  ]
                },
                "unit": "currencyUSD",
                "decimals": 4
              },
              "overrides": []
            },
            "options": {
              "reduceOptions": {
                "calcs": [
                  "lastNotNull"
                ],
                "fields": "",
                "values": false
              },
              "pieType": "pie",
              "tooltip": {
                "mode": "single",
                "sort": "none"
              },
              "legend": {
                "displayMode": "list",
                "placement": "right",
                "showLegend": true,
                "values": ["value"]
              }
            },
            "targets": [
              {
                "expr": "sum by (model) (claude_code_claude_code_cost_usage_USD_total)",
                "legendFormat": "{{model}}",
                "refId": "A"
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 24}
          },
          {
            "id": 11,
            "title": "Token Usage by Type",
            "type": "graph",
            "datasource": "Prometheus",
            "fieldConfig": {
              "defaults": {
                "custom": {
                  "axisLabel": "",
                  "axisPlacement": "auto",
                  "barAlignment": 0,
                  "drawStyle": "line",
                  "fillOpacity": 10,
                  "gradientMode": "none",
                  "hideFrom": {
                    "tooltip": false,
                    "viz": false,
                    "legend": false
                  },
                  "lineInterpolation": "linear",
                  "lineWidth": 1,
                  "pointSize": 5,
                  "scaleDistribution": {
                    "type": "linear"
                  },
                  "showPoints": "never",
                  "spanNulls": false,
                  "stacking": {
                    "group": "A",
                    "mode": "none"
                  },
                  "thresholdsStyle": {
                    "mode": "off"
                  }
                },
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "green",
                      "value": null
                    }
                  ]
                },
                "unit": "short"
              },
              "overrides": []
            },
            "options": {
              "legend": {
                "calcs": [],
                "displayMode": "list",
                "placement": "bottom",
                "showLegend": true
              },
              "tooltip": {
                "mode": "multi",
                "sort": "none"
              }
            },
            "targets": [
              {
                "expr": "sum by (model, type) (claude_code_claude_code_token_usage_tokens_total)",
                "legendFormat": "{{model}} - {{type}}",
                "refId": "A"
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 24}
          },
          {
            "id": 12,
            "title": "User Summary Table",
            "type": "table",
            "datasource": "Prometheus",
            "fieldConfig": {
              "defaults": {
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "green",
                      "value": null
                    }
                  ]
                },
                "custom": {
                  "align": "auto",
                  "cellOptions": {
                    "type": "auto"
                  },
                  "inspect": false
                }
              },
              "overrides": [
                {
                  "matcher": {
                    "id": "byName",
                    "options": "Total Cost"
                  },
                  "properties": [
                    {
                      "id": "unit",
                      "value": "currencyUSD"
                    }
                  ]
                },
                {
                  "matcher": {
                    "id": "byName", 
                    "options": "Total Tokens"
                  },
                  "properties": [
                    {
                      "id": "unit",
                      "value": "short"
                    }
                  ]
                }
              ]
            },
            "options": {
              "showHeader": true,
              "cellHeight": "sm",
              "footer": {
                "show": false,
                "reducer": ["sum"],
                "countRows": false,
                "fields": ""
              }
            },
            "targets": [
              {
                "expr": "sum by (user_email, organization_id) (claude_code_claude_code_cost_usage_USD_total)",
                "legendFormat": "",
                "refId": "A",
                "format": "table",
                "instant": true
              },
              {
                "expr": "sum by (user_email, organization_id) (claude_code_claude_code_token_usage_tokens_total)",
                "legendFormat": "",
                "refId": "B", 
                "format": "table",
                "instant": true
              },
              {
                "expr": "sum by (user_email, organization_id) (claude_code_claude_code_lines_of_code_count_total)",
                "legendFormat": "",
                "refId": "C",
                "format": "table", 
                "instant": true
              }
            ],
            "transformations": [
              {
                "id": "merge",
                "options": {}
              },
              {
                "id": "organize",
                "options": {
                  "excludeByName": {
                    "Time": true,
                    "organization_id": false
                  },
                  "indexByName": {},
                  "renameByName": {
                    "user_email": "User Email",
                    "organization_id": "Organization", 
                    "Value #A": "Total Cost ($)",
                    "Value #B": "Total Tokens",
                    "Value #C": "Lines of Code"
                  }
                }
              }
            ],
            "gridPos": {"h": 8, "w": 24, "x": 0, "y": 32}
          }
        ],
        "time": {
          "from": "now-6h",
          "to": "now"
        }
    }

  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'Claude Code Dashboards'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards