apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: claude-monitoring

resources:
- namespace.yaml
- otel-collector/configmap.yaml
- otel-collector/deployment.yaml
- otel-collector/service.yaml
- prometheus/configmap.yaml
- prometheus/pvc.yaml
- prometheus/deployment.yaml
- prometheus/service.yaml
- grafana/configmap.yaml
- grafana/pvc.yaml
- grafana/deployment.yaml
- grafana/service.yaml

labels:
- pairs:
    app.kubernetes.io/part-of: claude-monitoring

images:
- name: otel/opentelemetry-collector-contrib
  newTag: latest
- name: prom/prometheus
  newTag: latest
- name: grafana/grafana
  newTag: latest