apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: claude-monitoring-dev

namePrefix: dev-

resources:
- ../../base

patches:
- path: grafana-service-patch.yaml
  target:
    group: ""
    version: v1
    kind: Service
    name: grafana
- path: otel-collector-service-patch.yaml
  target:
    group: ""
    version: v1
    kind: Service
    name: otel-collector

labels:
- pairs:
    environment: dev

replicas:
- name: otel-collector
  count: 1
- name: prometheus
  count: 1
- name: grafana
  count: 1