apiVersion: v1
kind: Service
metadata:
  name: otel-collector
spec:
  type: NodePort
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
    nodePort: 30317
  - name: otlp-http
    port: 4318
    targetPort: 4318
    nodePort: 30318
  - name: metrics
    port: 8888
    targetPort: 8888
  - name: prometheus
    port: 8889
    targetPort: 8889